### ISSUE TITLE
ESOM Requires graphical enviroment

### ISSUE THREAD

**Issue by doomedramen** [amsesk/scgid#3]
If esom requires a graphical enviroment, does SCGid also need one, as the plan was to install and run this on a headless HPC enviroment?

**Comment by amsesk** [comment]
@doomedramen The region-selection portion of the ESOM pipeline requires manual use of the Databionics ESOM GUI (Java). We haven't yet implemented an automatic algorithm for this portion of the pipeline nor do we intend to; this decision is in line with how ESOM is intended to work. That said, every other aspect of SCGid can be run through an ssh session or job scheduler on your HPC environment of choice. We usually download the `kmers` directory following `scgid kmers train`, select our region locally in the Databionics ESOM GUI, and then upload the updated directory back to our cluster for subsequent steps.

I hope this has answered your question, but please feel free to clarify or ask another! Thanks for your interest in SCGid.
