### ISSUE TITLE
Missing INI file

### ISSUE THREAD

**Issue by ItIsI-Orient** [amsesk/scgid#5]
The `setup.py` mentions `logging_config.ini` but this file is missing from the master branch. Because of this I am not able to build SCGid with the following error:
```
error: can't copy 'scgid/logging_config.ini': doesn't exist or not a regular file
```

**Comment by amsesk** [comment]
Thanks for catching this. This reference to `logging_config.ini` is outdated and no longer needed. I have removed it from `setup.py`.

Please pull, try again, and let me know that the error is corrected.

**Comment by ItIsI-Orient** [comment]
Seems to be working correctly now. Thanks
